# Generated by Django 6.0.6 on 2026-06-24 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='date',
            new_name='date_added',
        ),
    ]
