# Generated by Django 6.0.6 on 2026-06-24 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_rename_date_entry_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='date',
            new_name='date_added',
        ),
    ]
